### ISSUE TITLE
When in HTML file has Javascript variable same name as bootstrap keywords

### ISSUE THREAD

**Issue by metrey** [yaph/b2tob3#3]
In HTML there is a block <script> tag and the variable example as: var btn; which could have the same name as bootstrap v3 keyword so the replacement is var btn; to var btn btn-default;

And might be more other cases that make it's wrong.

**Comment by yaph** [comment]
Sorry, not sure what you mean. Is something replaced that shouldn't or the other way around? Maybe you can add the problematic example file.

**Comment by metrey** [comment]
Example in HTML file has <script> tag as:

```
<script>
var btn = 'hello';
function hello() {
      alert(btn);
}
</script>
... and other html tags as normal.
```

After running the replacement, it replaces as following:

```
<script>
![sample-b2t0b3-converted](https://cloud.githubusercontent.com/assets/1000650/6225547/727772ca-b6be-11e4-967c-8cbef2b6bd8d.png)


var btn btn-default = 'hello';
function hello() {
      alert(btn btn-default);
}
</script>
```

**Comment by yaph** [comment]
Has what? Are you trolling?

**Comment by metrey** [comment]
![sample-b2t0b3-converted](https://cloud.githubusercontent.com/assets/1000650/6225560/afe58048-b6be-11e4-9c6c-3f2f2ce77bbf.png)

I attach again.
Let's see if you understand what I meant (See the red block)

**Comment by yaph** [comment]
I see the problem, but there is not a lot I can do about this. See the following example, where it is desirable to replace content in HTML files:

```
<style>
.span-2 { color: red }
</style>
```

In this case you would want to replace it woth col-md-2. If you don't want to replace contents of HTML files, separate them from your CSS files and run the script in the CSS directory. This way the HTML files are kept. Thanks for clarifying the issue!
