### ISSUE TITLE
Missing class changes

### ISSUE THREAD

**Issue by Hellowlol** [yaph/b2tob3#4]
Thanks for making this wonderful tool.

Is there any reason why there are so many "class changes" that are missing? 

I was just browsing the code and checked against http://getbootstrap.com/migration

**Comment by yaph** [comment]
In cases like bar or label it is to avoid replacing too many false positives. Also I'm not sure that the migration guide was as comprehensive as it is now when I wrote this.

**Comment by Hellowlol** [comment]
Ok, thanks for the fast response. I'm gonna add that i can from the guide then
